In [1]:
import numpy as np

In [2]:
# create 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# 2D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  #1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
np.arange(0,10,2).reshape(5,1)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Attributes of numpy
arr = np.array([2,4,6,8,10])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(5,)
5
int64
8


In [14]:
# Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
# Element wise operations
print("Addition :", arr1+arr2)
print("Substraction :", arr1-arr2)
print("Multiplition :", arr1*arr2)
print("division :", arr1/arr2)

Addition : [11 22 33 44 55]
Substraction : [ -9 -18 -27 -36 -45]
Multiplition : [ 10  40  90 160 250]
division : [0.1 0.1 0.1 0.1 0.1]


In [15]:
# Universal functions
arr = np.array([1,2,3,4,5])
# sqr root
print(np.sqrt(arr))
# exponential
print(np.exp(arr))
# Sine
print(np.sin(arr))
# natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [17]:
# Array sting and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr)
arr[0]
arr[0][0]
arr[1:,2:]
print(arr[0:2,1:])
# modify array
arr[0,0] = 100
print(arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3 4]
 [6 7 8]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [18]:
# Statistical concept
data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dv = np.std(data)
# Normalize the data
normalized_data = (data-mean)/std_dv
print("Normalized Data:", normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
